[project]
name = "eval"
version = "0.1.0"
# description = "Add your description here"
# readme = "README.md"
authors = [
    { name = "youkwan", email = "144937481+youkwan@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[dependency-groups]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"